Holiday-Secret-Santa/Secret-Santa-App

.circleci/config.yml

Committing the circleci folder with config.yml in order for circleci to see the existing config.yml file.
closes #6

added config.yml file

---

models/event.js
models/index.js
models/participant.js
utils/index.js

- develop participant table
- updated event model object
- develop event and participant associations 1-many  &   1-1
- changed model -> index js -> auto-generated sequelize
closes #40

Participant Model

---

models/gift.js
utils/index.js

In this branch, I added the following:
closes #49

Added gift DB model

---

graphqlSchema/schema.js
server.js

- Use graphql new schema format and root
- Implement Event graphql apis
closes #24

Exchange crud

---

graphqlSchema/schema.js

- Implemented schema implementation (root) for Participants /create, view, delete/. 
- Implemented additional queries
- Tested with db
closes #25 
closes #27

Participant graphql

---

client/package-lock.json
client/package.json
client/src/components/DateTimeInput/index.js
client/src/components/EventForm/EventForm.test.js
client/src/components/LogoutLink/LogOutLink.test.js
package-lock.json

85 date time input

---

graphqlSchema/schema.js
models/gift.js
models/participant.js
utils/index.js

- Developed schema Gifts and Input Type
- Updated **db** models relationships
- Developed CRUD Mutations
- Developed queries
closes #32

Graphql Gifts Apis  (CRUD)

---

client/src/components/Carousel/CarouselPage.js
client/src/components/Carousel/style.css
client/src/components/FooterComp/FooterComp.js
client/src/components/FooterComp/style.css
client/src/components/HomePageImgs/HomePageImgs.js
client/src/components/HomePageImgs/style.css
client/src/components/WelcomeMessage/WelcomeMsg.js
client/src/components/WelcomeMessage/style.css
client/src/pages/HomePage/HomePage.js
graphqlSchema/schema.js

- developed assign secret santa mutation
- added some CSS styles on the home page
closes #34

Graphql Apis Assign

---

graphqlSchema/schema.js

- Fixes graphql schema
- Fixes heroku deploy issues

Fix graphql schema

---

graphqlSchema/schema.js

-  Developed **Auto Assign Secret Santa Apis.** 
closes #33

Auto Assign Participant

---

client/src/actions/graphql.api.js
client/src/actions/graphql.api.test.js
client/src/actions/graphql.queries.js
client/src/actions/graphql.queries.test.js
client/src/pages/CreateEvent/CreateEvent.js
client/src/pages/CreateEvent/CreateEvent.test.js
client/src/pages/Events/Events.js

- Split graphql common code into reusable files

99 list events

---

client/src/actions/graphql.api.js
client/src/actions/graphql.api.test.js
client/src/actions/graphql.queries.js
client/src/actions/graphql.queries.test.js
client/src/components/NavigationBar/NavigationBar.js
client/src/components/NavigationBar/NavigationBar.test.js
client/src/pages/OrganizerEvent/OrganizerEvent.js
client/src/pages/OrganizerEvent/OrganizerEvent.test.js

In this branch, I added the following:
closes #103

Render Participant Info

---

client/src/actions/graphql.api.js
client/src/actions/graphql.api.test.js
client/src/actions/graphql.queries.js
client/src/actions/graphql.queries.test.js
client/src/pages/OrganizerEvent/OrganizerEvent.js
client/src/pages/OrganizerEvent/OrganizerEvent.test.js

In this branch, I added the following:
closes #105 
Pending passing

Rendered Event Info on Organizer Event Page

---

client/src/pages/OrganizerEvent/OrganizerEvent.js
client/src/pages/OrganizerEvent/OrganizerEvent.test.js

In this branch, I added the following items:
closes #107

Dynamically Add Participants

---

client/src/actions/graphql.api.js
client/src/actions/graphql.api.test.js
client/src/actions/graphql.queries.js
client/src/actions/graphql.queries.test.js
client/src/components/DetailCard/DetailCard.js
client/src/components/ModalPopUp/ModalPopUp.js
client/src/pages/OrganizerEvent/OrganizerEvent.js
client/src/pages/OrganizerEvent/OrganizerEvent.test.js
client/src/pages/RsvpEvent/RsvpEvent.js
graphqlSchema/schema.js
models/participant.js

- Added _auto-assign mutation_
- Connected UI to assign Santa to _API action_
- Populated RSVP Chart with real data
- Event date and time formatted
- Updates participants query to include Secret Santa
- Fixes test case
- Update rsvp status values
- Use form hook + reset fields
closes #83

83 random assign

---

config/config.json
package-lock.json
package.json
utils/inviteEmail.js

In this branch, the following items were added:
closes #26

Designed basic email template

---

client/src/actions/graphql.api.js
client/src/actions/graphql.queries.js
client/src/pages/AddGift/AddGift.js
client/src/pages/ParticipantEvent/ParticipantEvent.js
client/src/pages/ParticipantEvent/ParticipantEvent.test.js
config/config.json
graphqlSchema/schema.js
utils/index.js

111 render gift to participant

---

client/src/actions/graphql.api.js
client/src/actions/graphql.queries.js
client/src/pages/ParticipantEvent/ParticipantEvent.js

- Delete gift on participant view
closes #79

Delete gift on participant view

---

client/src/actions/graphql.api.js
client/src/actions/graphql.queries.js
client/src/pages/ParticipantEvent/ParticipantEvent.js
graphqlSchema/schema.js

- Implemented **_Secret Santa Gift Table_** functionality on Participant View.
- Added the validation `when a participant rejects the invitation` to random assignment functionality. 
- Updated name on the table `You are the Secret Santa for`  _**name updated**_ for  Participants that have already Secret Santa.
- Deployed and tested on Heroku
`Test example on Graphql playground for the query using to render the gifts associated with the Secret Santa `
`After making assignments you will be able to see the table with the Info for your Secret Santa name` and `the gifts **only** if the secret santa have already enter the gifts `
`step 1 : make assigments `
`step 2: check participant view`
`step 3: logout and enter with the participant email and add gifts` Participant View
`step 4: logout and …

Update Secret Santa Table

---

client/src/components/NavigationBar/NavigationBar.js
client/src/components/NavigationBar/NavigationBar.test.js
client/src/components/NavigationBar/style.css
client/src/pages/AddGift/AddGift.js
client/src/pages/AddGift/style.css
config/config.json

resolved #133 
Fixed background image issue and adjusted form position on addGift page.
Repositioned navbar tooltips so as not to cover icons.

133 improve ui addgift

---

README.md
config/config.json

In this branch, I added final updates to the readme. 
closes #138

Final updates to readme
